### ISSUE TITLE
Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by udeshx** [buddy-works/imgcmp#1]
I'm running in the Windows 10 CMD

First time running
Source: C:\Users\owner\Dropbox\Memes
Destination: C:\Users\owner\Dropbox\MemesCMP
Compression Level: 2
Force: true
Cannot read property 'data' of undefined
![d848b7fbf67f6302110d218e4708314a 1](https://user-images.githubusercontent.com/28942294/64344182-50422d80-d031-11e9-9232-f1dd474ddf0d.png)

**Comment by mical** [comment]
should be fixed in version 1.1.2

**Comment by udeshx** [comment]
I just tested 1.1.2 and the issue is solved and the library works.
Thanks for the library and the fix.
